Default: &defaults
  database: clearingstelle
  user: alios
  password: 
  poolsize: 10
  host: localhost
  port: 5432
Development:
  <<: *defaults

Test:
  database: test_test
  <<: *defaults

Staging:
  poolsize: 100
  <<: *defaults

Production:
  poolsize: 100
  <<: *defaults
