Default: &defaults
  database: clearingstelle.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: clearingstelle_test.sqlite3
  <<: *defaults

Staging:
  database: clearingstelle_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: clearingstelle_production.sqlite3
  poolsize: 100
  <<: *defaults